# tuned
sac:
  env: brax/halfcheetah
  agent_kwargs:
    activation: tanh
  num_envs: 128
  buffer_size: 1_000_000
  fill_buffer: 10_000
  batch_size: 512
  learning_rate: 0.00020495107742294415
  gradient_steps: 128
  total_timesteps: 5242880
  eval_freq: 32768
  gamma: 0.98
  tau: 0.995
  target_entropy_ratio: 0
  normalize_observations: true


# tuned
ppo:
  env: brax/halfcheetah
  agent_kwargs:
    activation: tanh
  num_envs: 32
  num_steps: 32
  num_epochs: 2
  num_minibatches: 2
  learning_rate: 0.0017203361125365498
  max_grad_norm: 5
  total_timesteps: 5242880
  eval_freq: 32768
  gamma: 0.99
  gae_lambda: 0.8
  clip_eps: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  normalize_observations: true


# tuned
ddpg:
  env: brax/halfcheetah
  agent_kwargs:
    activation: tanh
  num_envs: 128
  buffer_size: 1048576
  fill_buffer: 8192
  batch_size: 512
  learning_rate: 0.0004691896228409861
  gradient_steps: 128
  total_timesteps: 5242880
  eval_freq: 32768
  gamma: 0.99
  tau: 0.99
  max_grad_norm: 1
  exploration_noise: 0.2
