# tuned
sac:
  env: brax/humanoidstandup
  agent_kwargs:
    activation: tanh
  num_envs: 128
  buffer_size: 1048576
  fill_buffer: 8192
  batch_size: 256
  learning_rate: 0.00020366442026830908
  gradient_steps: 128
  total_timesteps: 5242880
  eval_freq: 32768
  gamma: 0.99
  tau: 0.99
  target_entropy_ratio: 0
  normalize_observations: true


# tuned
ppo:
  env: brax/humanoidstandup
  agent_kwargs:
    activation: tanh
  num_envs: 32
  num_steps: 32
  num_epochs: 2
  num_minibatches: 2
  learning_rate: 0.0017203361125365498
  max_grad_norm: 5
  total_timesteps: 5242880
  eval_freq: 32768
  gamma: 0.99
  gae_lambda: 0.8
  clip_eps: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  normalize_observations: true


# tuned
ddpg:
  env: brax/humanoidstandup
  agent_kwargs:
    activation: tanh
  num_envs: 128
  buffer_size: 1048576
  fill_buffer: 8192
  batch_size: 512
  learning_rate: 0.00020399223998555615
  gradient_steps: 128
  total_timesteps: 5242880
  eval_freq: 32768
  gamma: 0.95
  tau: 0.99
  max_grad_norm: 0.1
  exploration_noise: 0.5
  normalize_observations: true


# tuned
td3:
  env: brax/humanoidstandup
  actor_kwargs:
    activation: tanh
  critic_kwargs:
    activation: tanh
  num_envs: 128
  buffer_size: 1048576
  fill_buffer: 8192
  batch_size: 256
  learning_rate: 0.0001538065811598203
  gradient_steps: 128
  total_timesteps: 5242880
  eval_freq: 262144
  gamma: 0.99
  tau: 0.95
  max_grad_norm: 0.2
  exploration_noise: 0.8
  target_noise: 1.0
  target_noise_clip: 0.9
  policy_delay: 10
  normalize_observations: true
