ppo:
  # Note: not fitted (idk how, probably impossible within 250k timesteps)
  env: MountainCar-v0
  env_kwargs: null
  agent_kwargs:
    activation: tanh
  num_envs: 10
  num_steps: 20
  num_epochs: 5
  num_minibatches: 5
  learning_rate: 2.5e-4
  max_grad_norm: 0.5
  total_timesteps: 100_000
  eval_freq: 1000
  gamma: 0.99
  gae_lambda: 0.98
  clip_eps: 0.2
  ent_coef: 0.0
  vf_coef: 0.5

dqn:
  env: MountainCar-v0
  env_kwargs: null
  agent: DuelingQNetwork
  agent_kwargs:
    activation: tanh
  num_envs: 5
  buffer_size: 10_000
  fill_buffer: 1000
  batch_size: 100
  max_grad_norm: 10
  learning_rate: 0.005
  gradient_steps: 5
  total_timesteps: 100_000
  eval_freq: 1000
  target_update_freq: 200
  eps_start: 1
  eps_end: 0.05
  exploration_fraction: 0.5
  gamma: 1.0
  ddqn: true

sac:
  env: MountainCar-v0
  env_kwargs: null
  agent_kwargs:
    activation: tanh
  num_envs: 5
  buffer_size: 10_000
  fill_buffer: 1000
  batch_size: 100
  learning_rate: 0.005
  gradient_steps: 5
  total_timesteps: 50_000
  eval_freq: 500
  gamma: 1.0
  tau: 0.8
  target_entropy_ratio: 0.5
