# tuned
sac:
  env: brax/hopper
  agent_kwargs:
    activation: tanh
  num_envs: 128
  buffer_size: 1_000_000
  fill_buffer: 10_000
  batch_size: 128
  learning_rate: 0.0005720796166976961
  gradient_steps: 128
  total_timesteps: 5242880
  eval_freq: 32768
  gamma: 0.995
  tau: 0.95
  target_entropy_ratio: 0
  normalize_observations: true


# tuned
ppo:
  env: brax/hopper
  agent_kwargs:
    activation: tanh
  num_envs: 32
  num_steps: 32
  num_epochs: 9
  num_minibatches: 2
  learning_rate: 0.00025674088686342003
  max_grad_norm: 1
  total_timesteps: 5242880
  eval_freq: 32768
  gamma: 0.995
  gae_lambda: 0.95
  clip_eps: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  normalize_observations: true


# tuned
ddpg:
  env: brax/hopper
  agent_kwargs:
    activation: tanh
  num_envs: 128
  buffer_size: 1048576
  fill_buffer: 8192
  batch_size: 512
  learning_rate: 0.00014524424253732564
  gradient_steps: 128
  total_timesteps: 5242880
  eval_freq: 32768
  gamma: 0.995
  tau: 0.98
  max_grad_norm: 1
  exploration_noise: 0.2
  normalize_observations: true


# tuned
td3:
  env: brax/hopper
  actor_kwargs:
    activation: tanh
  critic_kwargs:
    activation: tanh
  num_envs: 128
  buffer_size: 1048576
  fill_buffer: 8192
  batch_size: 256
  learning_rate: 0.00018789279685460533
  gradient_steps: 128
  total_timesteps: 5242880
  eval_freq: 262144
  gamma: 0.995
  tau: 0.95
  max_grad_norm: 2
  exploration_noise: 0.5
  target_noise: 0.8
  target_noise_clip: 0.5
  policy_delay: 3
  normalize_observations: true
