# tuned
sac:
  env: brax/walker2d
  agent_kwargs:
    activation: tanh
  num_envs: 128
  buffer_size: 1048576
  fill_buffer: 8192
  batch_size: 256
  learning_rate: 0.00020366442026830908
  num_epochs: 128
  total_timesteps: 5242880
  eval_freq: 32768
  gamma: 0.99
  polyak: 0.99
  target_entropy_ratio: 0
  normalize_observations: true


# tuned
ppo:
  env: brax/walker2d
  agent_kwargs:
    activation: tanh
  num_envs: 32
  num_steps: 32
  num_epochs: 2
  num_minibatches: 2
  learning_rate: 0.0017203361125365498
  max_grad_norm: 5
  total_timesteps: 5242880
  eval_freq: 32768
  gamma: 0.99
  gae_lambda: 0.8
  clip_eps: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  normalize_observations: true


# tuned
ddpg:
  env: brax/walker2d
  agent_kwargs:
    activation: tanh
  num_envs: 128
  buffer_size: 1048576
  fill_buffer: 8192
  batch_size: 512
  learning_rate: 0.00014524424253732564
  num_epochs: 128
  total_timesteps: 5242880
  eval_freq: 32768
  gamma: 0.995
  polyak: 0.98
  max_grad_norm: 1
  exploration_noise: 0.2
  normalize_observations: true


# tuned
td3:
  env: brax/walker2d
  actor_kwargs:
    activation: tanh
  critic_kwargs:
    activation: tanh
  num_envs: 128
  buffer_size: 1048576
  fill_buffer: 8192
  batch_size: 256
  learning_rate: 0.00018789279685460533
  num_epochs: 128
  total_timesteps: 5242880
  eval_freq: 262144
  gamma: 0.995
  polyak: 0.95
  max_grad_norm: 2
  exploration_noise: 0.5
  target_noise: 0.8
  target_noise_clip: 0.5
  policy_delay: 3
  normalize_observations: true
