sac:
  env: navix/Navix-DoorKey-16x16-v0
  agent_kwargs:
    activation: swish
  num_envs: 128
  buffer_size: 131_072
  fill_buffer: 8_192
  batch_size: 128
  learning_rate: 0.0003
  num_epochs: 128
  total_timesteps: 1_048_576
  eval_freq: 131_072
  gamma: 0.8
  polyak: 0.995
  target_entropy_ratio: 0.9
  normalize_observations: false

ppo:
  env: navix/Navix-DoorKey-16x16-v0
  agent_kwargs:
    activation: tanh
  num_envs: 16
  num_steps: 128
  num_epochs: 2
  num_minibatches: 1
  learning_rate: 0.0003
  max_grad_norm: 1
  total_timesteps: 1_048_576
  eval_freq: 262_144
  gamma: 0.95
  gae_lambda: 0.9
  clip_eps: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  normalize_observations: false

dqn:
  env: navix/Navix-DoorKey-16x16-v0
  agent_kwargs:
    activation: relu
  num_envs: 128
  num_epochs: 128
  buffer_size: 131_072
  fill_buffer: 8_192
  batch_size: 512
  learning_rate: 0.0003
  max_grad_norm: 1
  total_timesteps: 1_048_576
  eval_freq: 131_072
  gamma: 0.95
  eps_start: 1.0
  eps_end: 0.01
  exploration_fraction: 0.5
  target_update_freq: 2_048
  ddqn: true
  normalize_observations: false

iqn:
  env: navix/Navix-DoorKey-16x16-v0
  agent_kwargs:
    activation: tanh
  num_envs: 128
  num_epochs: 128
  buffer_size: 131072
  fill_buffer: 8192
  batch_size: 256
  learning_rate: 0.0003
  kappa: 0.5
  num_tau_samples: 16
  num_tau_prime_samples: 64
  total_timesteps: 1048576
  eval_freq: 131072
  gamma: 0.9
  eps_start: 1.0
  eps_end: 0.01
  exploration_fraction: 0.1
  target_update_freq: 512
  normalize_observations: true

pqn:
  env: navix/Navix-DoorKey-16x16-v0
  total_timesteps: 1048576
  eval_freq: 262144
  eps_start: 1
  num_envs: 512
  num_steps: 128
  num_epochs: 16
  num_minibatches: 64
  learning_rate: 0.00012588527002965486
  max_grad_norm: 1
  eps_end: 0.1
  exploration_fraction: 0.3
  gamma: 0.8
  lambda_: 0.2
  normalize_observations: true
